[build]
builder = "nixpacks"

[build.environment]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"
NODE_VERSION = "18.x"

[build.commands]
build = "npm install && npm run build"
start = "cd dist && node index.js"

[deploy]
startCommand = "cd dist && node index.js"
