[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"
startCommand = "npm start"

[build.environment]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
