[build]
builder = "nixpacks"

[build.environment]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"
NODE_VERSION = "18.x"

[build.commands]
build = "npm install && npm run build"

[deploy]
startCommand = "node dist/src/index.js"
